version: "3.8"
services:
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=rentahouse
    volumes:
      - ./data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  backend:
    build: ./server
    restart: always
    env_file:
      - ./server/.env
    environment:
      - MARIADB_HOST=db
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
